# Site settings
title: Dema's Blog On Github
header-img: img/tepee.jpg
email: anton.demartini@gmail.com
description: "A nice blogging experience on github, with Jekyll"
baseurl: ""
url: "http://anton-dema.github.io"
twitter_username: dema
github_username:  anton-dema
facebook_username:  antonangelo
layout: default
comments: true

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]