# Site settings
title: Anton Sandox
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "hello"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: dema
github_username:  anton-dema
facebook_username:  antonangelo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
